apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-03-05T14:57:45Z"
  labels:
    app: web
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":3000,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-expose
    operation: Update
    time: "2021-03-05T14:57:45Z"
  name: web-expose
  namespace: default
  resourceVersion: "4429"
  uid: 14d13da1-480f-4c9e-8ada-2d04bad184f2
spec:
  clusterIP: 10.100.242.196
  clusterIPs:
  - 10.100.242.196
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30654
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}

